name: Run local instance of lookyloo to test that current repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  splash-container:
     runs-on: ubuntu-latest

     strategy:
       fail-fast: false
       matrix:
         python-version: ["3.8", "3.9", "3.10", "3.11"]

     steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: 'poetry'

      - name: Clone Redis
        uses: actions/checkout@v4
        with:
          repository: redis/redis
          path: redis-tmp
          ref: 7.2

      - name: Install and setup redis
        run: |
          mv redis-tmp ../redis
          pushd ..
          pushd redis
          make
          popd
          popd

      - name: Install system deps
        run: |
          sudo apt install libfuzzy-dev
          # playwright required deps.
          # sudo apt install libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxdamage1 libgbm1 libpango-1.0-0 libcairo2 libatspi2.0-0

      - name: Install & run lookyloo
        run: |
          echo LOOKYLOO_HOME="'`pwd`'" > .env
          cp config/generic.json.sample config/generic.json
          cp config/modules.json.sample config/modules.json
          poetry install -vvv
          poetry run playwright install
          poetry run playwright install-deps
          poetry run tools/validate_config_files.py --check
          poetry run tools/validate_config_files.py --update
          poetry run tools/3rdparty.py
          poetry run start

      - name: Clone PyLookyloo
        uses: actions/checkout@v4
        with:
          repository: Lookyloo/PyLookyloo
          path: PyLookyloo

      - name: Install pylookyloo and run test
        run: |
          pushd PyLookyloo
          poetry install
          poetry run python -m pytest tests/testing_github.py
          popd

      - name: Stop instance
        run: |
          poetry run stop

      - name: Logs
        if: ${{ always() }}
        run: |
          cat logs/*.log
          cat website/logs/*.log
