name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
        cache: 'poetry'

    - name: Install dependencies
      run: |
        sudo apt install libfuzzy-dev
        poetry install
        echo LOOKYLOO_HOME="`pwd`" >> .env
        poetry run tools/3rdparty.py

    - name: Make sure SRIs are up-to-date
      run: |
        poetry run tools/generate_sri.py
        git diff website/web/sri.txt
        git diff --quiet website/web/sri.txt

    - name: Run MyPy
      run: |
        poetry run mypy .
